const ADD_ARTICLE = "ADD_ARTICLE";
const DATA_LOADED = 'DATA_LOADED';
const DATA_REQUESTED = 'DATA_REQUESTED';
const API_ERRORED = 'API_ERRORED'

export { ADD_ARTICLE, DATA_LOADED, DATA_REQUESTED, API_ERRORED };